### PR TITLE
[ADD]add simple example using decorator

### PR DESCRIPTION
**Pull request by ChaeyeonSeo**
There is only one example in the folder 18-Decorators, which is quite difficult for beginners, so I add a simple example using decorator.

### CODE REVIEW

**Review by devquint — COMMENTED** [review]
As my understanding, decoration is kinda like Java's annotation, something expressed like `@~~~`.
However the added code seems not related to that expression. Could I request the details about the code?

**Comment by ChaeyeonSeo** [comment]
I refered to "http://schoolofweb.net/blog/posts/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EB%8D%B0%EC%BD%94%EB%A0%88%EC%9D%B4%ED%84%B0-decorator/" this link, and I understood that decoration is using decorator function and wrapper function. If it's wrong I would like to change the codes to using @~~~, so I wish you check it one more time, please. Thank  you.

**Review by devquint — COMMENTED** [review]
I checked [your reference website](http://schoolofweb.net/blog/posts/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EB%8D%B0%EC%BD%94%EB%A0%88%EC%9D%B4%ED%84%B0-decorator/), and according to it, maybe your added code the legacy/boilerplate code of the decorator grammer. 

I think implementing both style(decorator w/o `@` and decorator w/ `@`) is better. However with some changes of POV, the original code is some example w/ `@` and your new code is example is w/o `@`. 
Maybe listen to other's opinion would be better, how about yours?

**Comment by ChaeyeonSeo** [comment]
I just added this code since I thought that the code in the folder is too difficult for beginners, so I don't really matter which style it is. Then, is it okay to add the fourth code in that page?

**Comment by devquint** [comment]
I thought the ultimate purpose of using decorator grammar is reducing some boilerplate codes and displays short but certainly call the other method.

For example we need to implementing some server-related codes. (Not such a good example though)
Implementing method `adding` which receive two number via socket and respond their sum.
and another method `multiplying` which receive two number via socket and respond their multiplication.
Both need opening socket, bind, and some codes related to server.
Then if we use server-related method to decorator and and `adding` and `multiplying` just do some calculating.

In this case certainly call the adding-server method by 
```python
def open_server(original_function):
    def decorator(*args, **kwargs):
        some_server_opening_code(...);
        some_receiving_arguments_code(...);
        result = original_function(some_arguments)
        some_responding_code(result);
        some_server_closing_code(...);
        return result
    return decorator

def adding(...):
    ...

def multiplying(...):
    ...

open_server(adding)
```
would be good, but the **user of `adding` should know it should be used via `open_server(adding)`**

but if we use with `@`
```python
def with_server(original_function):
    def decorator(*args, **kwargs):
        ...
    return decorator

@with_server
def server_adding(...):
    ...

@with_server
def server_multiplying(...):
    ...

server_adding();
```
user can just use `server_adding` **without any detailed knowledge** about the method `server_adding`

Using decorator with `@` allow users to have less knowledge about the usage of method, and reducing some boilerplate `decorator(...)`.


With this POV I thought it would be better to explain decorator with `@`, not giving objection to your easier code. I surely agree to adding easier code.

---

요약(Summary in Korean): 

Decorator 문법의 궁극적인 목표가 `@`를 사용해서 사용자가 해당 함수가 데코레이터 문법을 사용해서 호출해야 하는 것(`decorator(function)`)인지 몰라도 바로 사용할 수 있게(`function`) 하고 보일러플레이트 코드(형식을 위해 넣어야 하는 긴 코드)를 조금이라도 줄이는 데 있다고 생각해서, `@`를 사용하는 예시도 쉽게 더 보여줬으면 좋겠다는 의미였습니다. 쉬운 코드를 추가하는 데는 전적으로 동의합니다.

**Comment by ChaeyeonSeo** [comment]
Thanks for your advice. I add another code, and I want to ask it could be a better code.

**Review by devquint — CHANGES_REQUESTED** [review]
I thinks is kinda good. 
However I thinks it needs some fixes

1. `print` **`()`**

line 3, 10, 15, 19
This maybe quite critical error, I cannot execute this code.

2. `funning` is intended?

Line 15, did you intended this out-of-grammar? This is just for double check.

3. Both using `@` and not using `@` would be better

In my opinion using both case would be better, making 
line 8: `@decorator_function` -> ` `
line 18: `display_1()` -> `decorator_function(display_1())`

Then reader might notice if we use `@ annotation at the function def` we don't need to wrap function call(function `display_2()`), while we should use wrap function call without `@ annotation`(function `display_1()` should be used `decorator_function(display_1())`).

**Comment by ChaeyeonSeo** [comment]
I fix all grammatical errors, and I also agree to your last advice, so update a code.  Thank you for reviewing!

**Review by devquint — APPROVED** [review]
I fixed small convention thing (deleted space between `print` and `()`), and I approved!

**Comment by Dorika0203** [comment]
I think the added code is quite good for beginners. This really helped me understand decorators. Let me merge this one.

**Pull request merged**
