### PR TITLE
Added more details to decorators_simple.py

### PR DESCRIPTION
**Pull request by devquint**
I added one more case that not using reassigning, and added comment to help understanding what the purpose of three functions.

Related PR: #8

### CODE REVIEW

**Review by Dorika0203 — APPROVED** [review]
Maybe display_1 would be better to be used as an example of normal function without decorators, but I think it's not really important. New example of normal function without decorating seems quite good.

**Comment by devquint** [comment]
> Maybe display_1 would be better to be used as an example of normal function without decorators, but I think it's not really important. New example of normal function without decorating seems quite good.

It was discussed at #8 and I thought her example was good to show that we can shorten the function without `@` annotation by reassigning, so I kept it.

**Comment by Dorika0203** [comment]
I understood. As this is code change, let's wait for other's approve, for safety.

**Review by jesusleejy — APPROVED** [review]
suitable comments has been added

**Pull request merged**
