### PR TITLE
[UPDATE] Changed folder name 'Slides' to '00 - Slides' in more-python-for-beginners

### PR DESCRIPTION
**Pull request by Hyuntae-Jeong**
Changed "Slides" Folders to "00 - Slides" in folder more-python-for-beginners
This action intended for users to find Slides folder first. Slides folders are placed at low bottom, so users might not easily find it

Slides폴더가 온라인 사이트에서 볼 때에 맨 밑에 위치하여 처음 방문하는 사용자가 슬라이드 폴더를 알아차리지 못하는 경우를 방지하기 위에 앞에 "00 - "을 추가하여 맨 위에 위치하도록 조정하였습니다

### CODE REVIEW

**Review by devquint — CHANGES_REQUESTED** [review]
Why the changes for the `python-for-beginners` are here too?

**Comment by Dorika0203** [comment]
I think it would be good to make a new branch derive from the branch "better-more-python-for-beginners", then change these file names. Commits of changing file names in "python-for-beginners" are here, too.

**Comment by Hyuntae-Jeong** [comment]
@Dorika0203 @devquint  How this problem happened? I've only added better-more-python-for-beginners, but files of python-for-beginners was added too.

**Comment by devquint** [comment]
Maybe you did make a branch based on previous branch that you've done some other commit.

**Comment by Dorika0203** [comment]
When we check out to new branch, we can sellect which branch will be the source branch.
git checkout -b [new branch] [source branch]
I think this new should be derived from "better-more-python-for-beginners".
However, it seems it didn't.
What I think is that when you checked out, you may be used "change-folder-name-1" as a source branch.
try this check out, if you are going to do this work again on new branch:
$git checkout -b change-folder-name-3 origin/better-more-python-for-beginners

**Comment by Hyuntae-Jeong** [comment]
@Dorika0203 @devquint  Thank you for your review. I will close this PR and make new one!
with $git checkout -b change-folder-name-3 origin/better-more-python-for-beginners command.

**Pull request closed without merging**
