### PR TITLE
Add coment 1

### PR DESCRIPTION
**Pull request by ChaeyeonSeo**

### CODE REVIEW

**Review by devquint — CHANGES_REQUESTED** [review]
1. Seems to be aligned badly

image


2. Better to adding one blank line between getter and setter

```python
# comment 1
code(1)

#comment 2
code(2)

#comment 3
code(3)
code(3)
```
Similar to the comment of #2 


3. You do not need to open new Pull Request even if you commit some more

Github will automatically refresh your original PR if you commit to the same branch even if you don't want to. Therefore you just keep the PR, and leave some comment that you changed some of the code according to the request. Then others can check it again with new commits.

**Comment by ChaeyeonSeo** [comment]
I rearrange the comments. It worked well in my local computer and also github site, but it doesn't look well on the commit page. You can see it works well in the branch "add-coment-1", so please check it and merge this PR.

**Review by devquint — CHANGES_REQUESTED** [review]
I checked your `c47e8a6` commit, but it seems not good either.

It seems to be a mixture of tab(`\t`) and spaces(maybe 6 spaces). Python 3 DISALLOW the mixture of tab and spaces.

[PEP 8 recommends 4 space for indent](https://pep8.org/#indentation), but it seems this project uses tab for indentation. Please check line 6, 7, 13 and so on again.

**Comment by ChaeyeonSeo** [comment]
I rearrange it again. Thank you for reviewing.

**Review by devquint — APPROVED** [review]

**Pull request merged**
